[package]
name = "server"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", default-features = false, features = [
    "http2",
    "json",
    "matched-path",
    "original-uri",
    "tokio",
    "tower-log",
    "form",
    "query",
    "ws",
] }
tokio = { version = "1.32.0", features = ["full"] }
log = "0.4.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
uuid = { version = "1.4.1", features = ["v4"] }
toml = "0.7.6"
futures = "0.3.28"
redb = { version = "1.1.0", default-features = false }

[dev-dependencies]
tower = { version = "0.4.13", features = ["util"] }
hyper = { version = "0.14.27", features = ["full"] }
