[package]
name = "server"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.2", default-features = false, features = [
    "http2",
    "json",
    "matched-path",
    "original-uri",
    "tokio",
    "tower-log",
    "form",
    "query",
    "ws",
    "multipart",
] }
tokio = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { version = "1.6.1", features = ["v4"] }
toml = { workspace = true }
futures = "0.3.30"
flate2 = { workspace = true }
rust-embed = "8.1.0"
common = { path = "../common" }
glob = { workspace = true }

[dev-dependencies]
tower = { version = "0.4.13", features = ["util"] }
hyper = { version = "1.1.0", features = ["full"] }
