[package]
name = "server"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", default-features = false, features = [
    "http2",
    "json",
    "matched-path",
    "original-uri",
    "tokio",
    "tower-log",
    "form",
    "query",
    "ws",
    "multipart",
] }
tokio = { version = "1.33.0", features = ["full"] }
log = "0.4.20"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
uuid = { version = "1.5.0", features = ["v4"] }
toml = "0.8.8"
futures = "0.3.29"
flate2 = "1.0.28"
rust-embed = "8.0.0"
common = {path = "../common"}
glob = "0.3.1"

[dev-dependencies]
tower = { version = "0.4.13", features = ["util"] }
hyper = { version = "0.14.27", features = ["full"] }
