pub(crate) mod collect;
pub(crate) mod enrollment;
pub(crate) mod footer;
pub(crate) mod host;
pub(crate) mod host_navigation;
pub(crate) mod jobs;
pub(crate) mod menu;
pub(crate) mod rust;
pub(crate) mod stats;
