name: Stable Release Cross

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  upload-release-cross:
    strategy:
      matrix:
        info:
          - os: "ubuntu-latest"
            target: "aarch64-unknown-linux-gnu"
    runs-on: ${{ matrix.info.os }}
    steps:
      - name: Setup NodeJS toolchain
        uses: actions/setup-node@v4
      - name: Install TailwindCSS
        run: npm install -D tailwindcss
      - name: Install DaisyUI
        run: npm install -D daisyui@latest
      - name: Install TailwindCSS Typography
        run: npm install -D @tailwindcss/typography
      - name: Setup Stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt
      - name: Setup Cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      # Compile WASM before compiling binary
      - name: Compile WASM
        run: just _wasm

      - name: Build Artemis
        shell: bash
        run: just --shell bash --shell-arg -uc _ci_release_cross ${{ matrix.info.target }}

      - name: Package Artemis
        shell: bash
        env:
          NAME: artemis
          TARGET: ${{ matrix.info.target }}
        run: .github/scripts/package.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "artemis*"
          name: "${{ vars.GITHUB_REF_NAME }} - Released!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
