name: Stable Release Packages

on:
  push:
    tags:
      - v[0-9]+.*

permissions: {}

jobs:
  build:
    name: Compile Package Releases
    strategy:
      matrix:
        info:
          - os: "macOS-latest"
            target: "x86_64-apple-darwin"
          - os: "macOS-latest"
            target: "aarch64-apple-darwin"
          - os: "windows-latest"
            target: "x86_64-pc-windows-msvc"
          - os: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
          - os: "windows-11-arm"
            target: "aarch64-pc-windows-msvc"
    runs-on: ${{ matrix.info.os }}
    permissions:
      contents: read
    steps:
      - name: Setup Stable Rust toolchain
        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 #v2025.09.23
        with:
          targets: ${{ matrix.info.target }}
          components: clippy, rustfmt
          toolchain: stable
      - name: Setup Auditable
        run: cargo install cargo-auditable

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@5597bc27da443ba8bf9a3bc4e5459ea59177de42 #v2.62.4
        with:
          tool: just

      # macOS Package Option
      - name: Setup runner Keychain
        if: matrix.info.os == 'macOS-latest'
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          DEVELOPER_P12: ${{ secrets.DEVELOPER_P12 }}
        run: |
          echo $DEVELOPER_P12 | base64 --decode > certs.p12
      
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          security import certs.p12 -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Create Keychain Profile
        if: matrix.info.os == 'macOS-latest'
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_PASS: ${{ secrets.APP_PASS }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: xcrun notarytool store-credentials "PuffyCid" --apple-id "$APPLE_ID" --password "$APP_PASS" --team-id "$TEAM_ID" --keychain $RUNNER_TEMP/app-signing.keychain-db

      - name: Create PKG, sign, and notarize
        if: matrix.info.os == 'macOS-latest'
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
          TARGET: ${{ matrix.info.target }}
          VERSION: ${{  github.ref_name }}
        run: just _ci_pkg $VERSION PuffyCid $TARGET


      # Windows Package Options
      - name: Install dotnet
        if: matrix.info.os == 'windows-latest'
        run: choco install dotnet

      - name: Install WiX
        if: matrix.info.os == 'windows-latest'
        run: dotnet tool install --global wix

      - name: Package Artemis as MSI
        if: matrix.info.os == 'windows-latest'
        env:
          TARGET: ${{ matrix.info.target }}
        run: just --shell pwsh.exe --shell-arg -c _ci_msi $TARGET

      # Windows ARM Package Options
      - name: Install WiX on Windows ARM
        if: matrix.info.os == 'windows-11-arm'
        run: dotnet tool install --global wix

      - name: Package Artemis as MSI on Windows ARM
        if: matrix.info.os == 'windows-11-arm'
        env:
          TARGET: ${{ matrix.info.target }}
        run: just --shell pwsh.exe --shell-arg -c _ci_msi $TARGET

      # Linux Package Options
      - name: Install RPM tools
        if: matrix.info.os == 'ubuntu-latest'
        run: | 
          sudo apt install -y rpm gnupg2 debsigs
          mkdir -p ~/.gnupg/

      - name: Import GPG Key
        if: matrix.info.os == 'ubuntu-latest'
        env: 
          KEY: ${{ secrets.GPG_KEY }}
        run: | 
          echo "$KEY" | base64 --decode | gpg --batch --yes --import

      - name: Package Artemis as RPM
        if: matrix.info.os == 'ubuntu-latest'
        shell: bash
        env:
          NAME: artemis
          TARGET: ${{ matrix.info.target }}
          VERSION: ${{  github.ref_name }}
        run: just _ci_rpm $TARGET

      - name: Package Artemis as DEB
        if: matrix.info.os == 'ubuntu-latest'
        shell: bash
        env:
          NAME: artemis
          TARGET: ${{ matrix.info.target }}
          VERSION: ${{  github.ref_name }}
          PUB: ${{ secrets.GPG_PUB }}
        run: just _ci_deb $VERSION $TARGET

  package:
    name: Publish Artemis Packages
    strategy:
      matrix:
        info:
          - os: "macOS-latest"
            target: "x86_64-apple-darwin"
          - os: "macOS-latest"
            target: "aarch64-apple-darwin"
          - os: "windows-latest"
            target: "x86_64-pc-windows-msvc"
          - os: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
          - os: "windows-11-arm"
            target: "aarch64-pc-windows-msvc"
    runs-on: ${{ matrix.info.os }}
    permissions:
      contents: write # Used to publish releases
    needs: [build]
    steps:
      - name: Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 #v2.3.3
        with:
          files: "target/${{matrix.info.target}}/release-action/artemis*"
          name: "${{ github.ref_name }} - Released!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}