name: Stable Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  upload-assets:
    strategy:
      matrix:
        info:
          - os: "ubuntu-latest"
            target: "aarch64-unknown-linux-gnu"
          - os: "macOS-latest"
            target: "x86_64-apple-darwin"
          - os: "macOS-latest"
            target: "aarch64-apple-darwin"
          - os: "windows-latest"
            target: "x86_64-pc-windows-msvc"
          - os: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
    runs-on: ${{ matrix.info.os }}
    steps:
      - name: Setup NodeJS toolchain
        uses: actions/setup-node@v4
      - name: Install TailwindCSS
        run: npm install -D tailwindcss
      - name: Install DaisyUI
        run: npm install -D daisyui@latest
      - name: Install TailwindCSS Typography
        run: npm install -D @tailwindcss/typography
      - name: Add WASM Support
        run: rustup target add wasm32-unknown-unknown
      - name: Setup Auditable
        run: cargo install cargo-auditable && shopt -s expand_aliases && alias cargo="cargo auditable"
      - if: matrix.info.os != 'windows-latest'
        name: Setup Auditable
        run: cargo install cargo-auditable && shopt -s expand_aliases && alias cargo="cargo auditable"
      - if: matrix.info.os == 'windows-latest'
        name: Setup Auditable
        run: cargo install cargo-auditable
      - if: matrix.info.os == 'windows-latest'
        name: Configure Auditable
        run: function cargo {cargo.exe auditable $args}

      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"
      # Compile WASM before compiling binary
      - if: matrix.info.os == 'windows-latest'
        run: just --shell pwsh.exe --shell-arg -c _wasm
      - if: matrix.info.os != 'windows-latest'
        run: just _wasm
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: artemis
          target: ${{ matrix.info.target }}
          archive: $bin-$tag-$target
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
