name: Stable Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  upload-release:
    strategy:
      matrix:
        info:
          - os: "macOS-latest"
            target: "x86_64-apple-darwin"
          - os: "macOS-latest"
            target: "aarch64-apple-darwin"
          - os: "windows-latest"
            target: "x86_64-pc-windows-msvc"
          - os: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
    runs-on: ${{ matrix.info.os }}
    steps:
      - name: Setup NodeJS toolchain
        uses: actions/setup-node@v4
      - name: Install TailwindCSS
        run: npm install -D tailwindcss
      - name: Install DaisyUI
        run: npm install -D daisyui@latest
      - name: Install TailwindCSS Typography
        run: npm install -D @tailwindcss/typography
      - name: Setup Stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.info.target }}
          components: clippy, rustfmt
      - name: Setup Auditable
        run: cargo install cargo-auditable

      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just

      - name: Tauri build dependencies on Linux
        if: matrix.info.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install libgtk-3-dev libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Build Artemis
        run: just _ci_release ${{ matrix.info.target }}

      - name: Package Artemis
        shell: bash
        env:
          NAME: artemis
          TARGET: ${{ matrix.info.target }}
        run: .github/scripts/package.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "artemis*"
          name: "${{ vars.GITHUB_REF_NAME }} - Released!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}