name: GitHub Actions Security Analysis with zizmor

on:
  pull_request:
    branches: 
      - "main"

permissions: {}

jobs:
  zizmor:
    name: Run zizmor 
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for zizmor
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@e673c3917a1aef3c65c972347ed84ccd013ecda4 # v0.2.0
        with:
            persona: auditor