name: GitHub Actions Security Analysis with zizmor

on:
  pull_request:
    branches: 
      - "main"

permissions: {}

jobs:
  zizmor:
    name: Run zizmor 
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for zizmor
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@e673c3917a1aef3c65c972347ed84ccd013ecda4 # v0.2.0
        with:
            persona: auditor

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3 # v3.30.3
        with:
          sarif_file: results.sarif
          category: zizmor